unit TestFrmMain;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, Vcl.Graphics, Vcl.StdCtrls, Winapi.Windows,
  System.Variants, Vcl.Dialogs, Vcl.Controls, Vcl.Forms, Winapi.Messages, uFrmMain,
  System.Classes;

type
  // Test methods for class TFrmPrincipal
  TestTFrmPrincipal = class(TTestCase)
  strict private
    FFrmPrincipal: TFrmPrincipal;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestbtnCalcularConsumoClick;
  end;

implementation

procedure TestTFrmPrincipal.SetUp;
begin
  FFrmPrincipal := TFrmPrincipal.Create(nil);
end;

procedure TestTFrmPrincipal.TearDown;
begin
  FFrmPrincipal.Free;
  FFrmPrincipal := nil;
end;

procedure TestTFrmPrincipal.TestbtnCalcularConsumoClick();
begin
  FFrmPrincipal.edtKmInicial.Text := '10000';
  FFrmPrincipal.edtKmFinal.Text := '11000';
  FFrmPrincipal.edtMediaConsumo.Text := '10';
  FFrmPrincipal.edtValorLitro.Text := '4';
  FFrmPrincipal.btnCalcularConsumoClick(nil);
  Assert(FFrmPrincipal.edtValorFinal.Text = '400');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFrmPrincipal.Suite);
end.

